from enum import Enum
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field
import time
import uuid

class SecurityLabel(str, Enum):
    TRUSTED_SYSTEM = "TRUSTED_SYSTEM"         # Hardcoded system instructions, verified configs
    TRUSTED_USER = "TRUSTED_USER"             # Direct user input prompt
    MODEL_GENERATED = "MODEL_GENERATED"       # Output generated by an agent LLM
    RETRIEVED_EXTERNAL = "RETRIEVED_EXTERNAL" # External documentation, vector chunks
    TOOL_OUTPUT = "TOOL_OUTPUT"               # Output produced by executed tools
    UNTRUSTED_EXTERNAL = "UNTRUSTED_EXTERNAL" # Untrusted websites, external APIs
    POTENTIAL_INJECTION = "POTENTIAL_INJECTION" # Flagged content carrying injection payloads


class ProvenanceMetadata(BaseModel):
    provenance_id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    source: str                                # E.g. "faiss_index", "duckduckgo", "user_prompt", "agent_architect"
    trust_level: float = 1.0                  # 0.0 (completely untrusted) to 1.0 (authoritative)
    origin: str                                # Originating URL, file, or prompt id
    timestamp: float = Field(default_factory=time.time)
    agent: Optional[str] = None                # Agent creating or processing this data
    content_type: str = "text"                 # "text", "code", "json", "triplet"
    security_label: SecurityLabel = SecurityLabel.MODEL_GENERATED
    parent_operation: Optional[str] = None     # Id of the operation that generated this

    def is_trusted_for_tool_execution(self) -> bool:
        """
        Policy: Only TRUSTED_SYSTEM, TRUSTED_USER, or verified MODEL_GENERATED
        can directly instruct tool invocations.
        UNTRUSTED_EXTERNAL and RETRIEVED_EXTERNAL can NEVER directly authorize tools.
        """
        forbidden_labels = {
            SecurityLabel.UNTRUSTED_EXTERNAL,
            SecurityLabel.RETRIEVED_EXTERNAL,
            SecurityLabel.POTENTIAL_INJECTION
        }
        return self.security_label not in forbidden_labels and self.trust_level >= 0.70

    def to_dict(self) -> Dict[str, Any]:
        return {
            "provenance_id": self.provenance_id,
            "source": self.source,
            "trust_level": self.trust_level,
            "origin": self.origin,
            "timestamp": self.timestamp,
            "agent": self.agent,
            "content_type": self.content_type,
            "security_label": self.security_label.value,
            "parent_operation": self.parent_operation
        }
